version: '3.5'

services:
  postgres:
    image: postgres:${PG_VERSION:-alpine}
    container_name: postgresql
    restart: unless-stopped
    ports:
      - ${PG_PORT:-127.0.0.1:5432}:5432
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASS:-postgres}
