version: '3.5'

volumes:
  postgresql-9:
    name: postgresql-9
  postgresql-12:
    name: postgresql-12

services:
  pg9:
    image: postgres:9-alpine
    container_name: pg9
    restart: unless-stopped
    network_mode: host
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql-9:/var/lib/postgresql/data

  pg12:
    image: postgres:12-alpine
    container_name: pg12
    restart: unless-stopped
    network_mode: host
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql-12:/var/lib/postgresql/data