name: postgresql
services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-16-alpine}
    container_name: postgresql
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT:-127.0.0.1:5432}:5432
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
